import { createSlice } from "@reduxjs/toolkit";

export const counterSlice = createSlice({
  name: "counter", // A unique name for the slice
  initialState: {
    value: 0, // Initial state for the slice
  },
  reducers: {
    // The methods that can modify the state
    increment: (state) => {
      // Redux Toolkit uses Immer, which allows us to "mutate" the state
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
  },
});

export default counterSlice.reducer;

// Export the actions generated by createSlice
export const { increment, decrement } = counterSlice.actions;
